### ISSUE TITLE
Setting attributes in node or role file not working

### ISSUE THREAD

**Issue by jbwyatt4** [matschaffer/knife-solo#479]
Hello,

I've attached a role to demonstrate (.txt was added because github didn't like a json file). I test for the attributes in the recipe with:

p node.override
p node.attribute?("r_version")

I keep getting false or nil every time.

[ubuntu-rails-app-server.json.txt](https://github.com/matschaffer/knife-solo/files/130196/ubuntu-rails-app-server.json.txt)

Using knife-solo 0.5.1

**Comment by matschaffer** [comment]
The chef solo json files don't take default/overrides like this since they're always the final override on top of everything else.

See https://docs.chef.io/chef_solo.html for details. Specifically the "Attributes" section and the warning section where `--json-attributes` is covered.

Hope that helps!

**Comment by jbwyatt4** [comment]
I'm afraid I don't understand it that well. How would I override a normal attribute using the node or role file with chef-solo?

**Comment by matschaffer** [comment]
Node is different than role. Node would just be `{"attribute_name": "attribute_value"}` at the top level of the JSON hash. For a role I'd recommend using a .rb role and a `default_attributes` call like the one shown in https://docs.chef.io/roles.html

**Comment by jbwyatt4** [comment]
Thankyou! Got it working.

**Comment by matschaffer** [comment]
:+1:
